# config.py

PROJECT_NAME = "TEKNOFEST IHA GOREV SISTEMI"

MODEL_PATH = "best.pt"

CAMERA_INDEX = 0

FRAME_WIDTH = 640
FRAME_HEIGHT = 480

CONF_LIMIT = 0.50
IOU_LIMIT = 0.10
MAX_DETECTION = 1

CENTER_TOLERANCE = 80
STABLE_LIMIT = 5

MISSION_SEQUENCE = [
    "kirmizi_ucgen",
    "mavi_altigen"
]

VIDEO_OUTPUT_NAME = "test_kaydi.mp4"

SERVO_TRIANGLE_PIN = 17
SERVO_HEXAGON_PIN = 27