# state_machine.py

class MissionState:

    IDLE = "IDLE"

    TAKEOFF = "TAKEOFF"

    MISSION_1_INFINITY8 = "MISSION_1_INFINITY8"

    MISSION_2_SEARCH = "MISSION_2_SEARCH"

    TARGET_LOCK = "TARGET_LOCK"

    APPROACH = "APPROACH"

    DESCEND = "DESCEND"

    DROP_PAYLOAD = "DROP_PAYLOAD"

    ASCEND = "ASCEND"

    RETURN_TO_SEARCH = "RETURN_TO_SEARCH"

    LAND = "LAND"

    FINISHED = "FINISHED"